# Generated by Django 4.1.7 on 2023-02-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[{'S', 'Small'}, {'Medium', 'M'}, {'Large', 'L'}], default='Medium', max_length=100),
        ),
    ]
