# Generated by Django 4.1.7 on 2023-02-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_order_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[{'Small', 'S'}, {'Medium', 'M'}, {'L', 'Large'}], default='M', max_length=100),
        ),
    ]
